name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Do not raise issues, talk to the team lead @e.u'' first issue'
        pr-message: 'Welcome to TEAM INCREDIBLE, your pr will be attended to soon, you can message @tobi to fastedn the process'' first pr'
